// Mock database store for running local testing without MongoDB
const initialProducts = [
  {
    _id: 'prod1',
    name: 'Edifice Chronograph EFR-573',
    brand: 'Casio',
    category: 'Analog',
    price: 9995,
    originalPrice: 12495,
    description: 'A sporty classic chronograph watch featuring stopwatch functions, retro dial face highlights, mineral glass protection, and 100m water resistance. Ideal for professional and casual styles alike.',
    images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=600'],
    stock: 12,
    isFeatured: true,
    isTrending: true,
    tags: ['sporty', 'chronograph', 'metal'],
    rating: 4.5,
    numReviews: 8,
  },
  {
    _id: 'prod2',
    name: 'Presage Cocktail Time SRPB43',
    brand: 'Seiko',
    category: 'Luxury',
    price: 34500,
    originalPrice: 38000,
    description: 'Inspired by fine cocktails, this dress watch features a stunning ice-blue dial with a sunburst pattern. Powered by Seiko 4R35 automatic movement with a 41-hour power reserve. Completed with a black leather strap.',
    images: ['https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=600'],
    stock: 5,
    isFeatured: true,
    isTrending: false,
    tags: ['automatic', 'dress', 'leather'],
    rating: 4.8,
    numReviews: 12,
  },
  {
    _id: 'prod3',
    name: 'Gen 6 Smartwatch Charcoal',
    brand: 'Fossil',
    category: 'Smart',
    price: 18495,
    originalPrice: 22995,
    description: 'Fossil Gen 6 features always-on AMOLED displays, rapid charging, and Snapdragon Wear 4100+ processors. Track heart rate, blood oxygen levels, sleep quality, and receive calls/texts.',
    images: ['https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=600'],
    stock: 8,
    isFeatured: false,
    isTrending: true,
    tags: ['smart', 'digital', 'fitness'],
    rating: 4.2,
    numReviews: 24,
  },
  {
    _id: 'prod4',
    name: 'ProTrek Digital PRG-240',
    brand: 'Casio',
    category: 'Sports',
    price: 11995,
    originalPrice: 14500,
    description: 'Tough solar powered outdoor watch featuring a triple sensor (compass, altimeter/barometer, thermometer), low temperature resistance, duplex LCD display, and double lock resin band.',
    images: ['https://images.unsplash.com/photo-1539874754764-5a96559165b0?auto=format&fit=crop&q=80&w=600'],
    stock: 2,
    isFeatured: false,
    isTrending: true,
    tags: ['solar', 'sensor', 'outdoor'],
    rating: 4.6,
    numReviews: 15,
  },
  {
    _id: 'prod5',
    name: 'Minimalist Three-Hand Black Leather',
    brand: 'Fossil',
    category: 'Casual',
    price: 7995,
    originalPrice: 7995,
    description: 'A slim watch casing built with premium brushed steel, clean dial hour markings, and high-quality brown leather straps. Clean watch for everyday office wear.',
    images: ['https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&q=80&w=600'],
    stock: 15,
    isFeatured: true,
    isTrending: false,
    tags: ['minimalist', 'classic', 'casual'],
    rating: 4.4,
    numReviews: 6,
  },
  {
    _id: 'prod6',
    name: 'Submariner Date Oystersteel',
    brand: 'Rolex',
    category: 'Luxury',
    price: 850000,
    originalPrice: 900000,
    description: 'The Rolex Submariner is the benchmark for divers watches. Features a black Cerachrom bezel, luminescent dial indices, Oystersteel metal band, and chronometer certified automatic movement.',
    images: ['https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&q=80&w=600'],
    stock: 1,
    isFeatured: true,
    isTrending: true,
    tags: ['rolex', 'automatic', 'luxury'],
    rating: 5.0,
    numReviews: 4,
  }
];

const mockStore = {
  products: [...initialProducts],
  users: [
    {
      _id: 'user1',
      name: 'Admin User',
      email: 'admin@chrono.com',
      password: '$2a$10$wKlh8o6FidSg4F03lE84.O32c4jP6h1w503f12457812ab5678912', // crypted hash
      role: 'admin',
      addresses: [
        {
          _id: 'addr1',
          fullName: 'Admin Chrono',
          phone: '+91 98765 43210',
          street: '123 Watch Street',
          city: 'Mumbai',
          state: 'Maharashtra',
          pincode: '400001',
          isDefault: true,
        }
      ],
      phone: '+91 98765 43210',
    },
    {
      _id: 'user2',
      name: 'Admin Pro',
      email: 'pro4134@gmail.com',
      password: '$2a$10$tZ2zVqZ9Q.o2kQ6x7w8q/Oq2VqZ9Q.o2kQ6x7w8q/Oq2VqZ9Q.o2k', // will bypass in controller or compare
      role: 'admin',
      addresses: [],
      phone: '917081271482',
    }
  ],
  orders: [],
};

module.exports = mockStore;
